#!/usr/bin/env -S Rscript --vanilla

doc <-
    base::as.character(
"
curatedMetagenomicData - Curated Metagenomic Data of the Human Microbiome

The curatedMetagenomicData command-line interface provides standardized, curated
human microbiome data for novel analyses. It includes gene families, marker
abundance, marker presence, pathway abundance, pathway coverage, and relative
abundance for samples collected from different body sites. The bacterial,
fungal, and archaeal taxonomic abundances for each sample were calculated with
MetaPhlAn3, and metabolic functional potential was calculated with HUMAnN3. The
manually curated sample metadata and standardized metagenomic data are available
through this command-line interface.

Usage:
    curatedMetagenomicData <pattern>
    curatedMetagenomicData <pattern> --dryrun
    curatedMetagenomicData <pattern> --counts
    curatedMetagenomicData <pattern> --metadata

Arguments:
    <pattern> a regular expression pattern to look for in the titles of
              resources available in curatedMetagenomicData; \".\" will return all

Options:
    --dryrun    return only names of resources
    --counts    return taxa abundances as counts
    --metadata  return only subject metadata

Return Value:
    A table of tab-seperated values will be sent to stdout. Where multiple
    studies of the same data type are requested, they will be merged into a
    single table. Where the metadata option (--metadata) is specified, the
    returned table will contain only metadata.

Examples:
    To return the names of all resources matching \"AsnicarF_20.+\", the following
    command is used and will return all data types for both \"AsnicarF\" studies.

        # curatedMetagenomicData \"AsnicarF_20.+\" --dryrun

    To return the relative abundance table for the \"AsnicarF_2017\" study, the
    following command is used and will return a tab-seperated table to stdout.

        # curatedMetagenomicData \"AsnicarF_2017.relative_abundance\"

    To return a relative abundance table for both \"AsnicarF\" studies converted
    to read counts (i.e. relative abundance * read depth), the following command
    is used and will return a tab-seperated table to stdout.

        # curatedMetagenomicData \"AsnicarF_20.+.relative_abundance\" --counts

    To return a table containing only metadata for both \"AsnicarF\" studies, the
    metadata option (--metadata) is specified and will return a tab-seperated
    table to stdout.

        # curatedMetagenomicData \"AsnicarF_20.+.relative_abundance\" --metadata

"
    )

input <-
    try(docopt::docopt(doc, help = FALSE), silent = TRUE)

if (base::inherits(input, "try-error")) {
    base::cat(doc)

    base::quit()
}

if (input[["dryrun"]]) {
    curatedMetagenomicData::curatedMetagenomicData(input[["pattern"]])

    base::quit()
}

if (input[["pattern"]] == ".") {
    if (input[["metadata"]]) {
        curatedMetagenomicData::sampleMetadata |>
            readr::write_tsv(base::stdout())

        base::quit()
    }
}

output <-
    base::suppressMessages(
        curatedMetagenomicData::curatedMetagenomicData(
            input[["pattern"]],
            dryrun = input[["dryrun"]],
            counts = input[["counts"]]
        )
    ) |>
    curatedMetagenomicData::mergeData()

if (input[["metadata"]]) {
    output |>
        SummarizedExperiment::colData() |>
        base::as.data.frame() |>
        tibble::rownames_to_column(var = "sample_id") |>
        readr::write_tsv(base::stdout())

    base::quit()
}

output |>
    SummarizedExperiment::assay() |>
    base::as.data.frame() |>
    tibble::rownames_to_column() |>
    readr::write_tsv(base::stdout())
